# Unsupervised Learning Models K-Means Clustering

In [4]:
import numpy as np
import pandas as pd

from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

In [6]:
n_samples=300
random_state=20

X,y=make_blobs(n_samples=n_samples,n_features=5,random_state=None)

In [7]:
predict_y=KMeans(n_clusters=3,random_state=random_state).fit_predict(X)

In [8]:
predict_y

array([0, 2, 1, 1, 2, 0, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 1, 2, 1, 2, 0, 2,
       2, 0, 1, 1, 1, 1, 2, 0, 0, 0, 2, 0, 1, 1, 0, 2, 0, 2, 2, 1, 0, 1,
       1, 2, 2, 2, 1, 2, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 1, 2, 1, 0, 1, 1,
       0, 1, 0, 2, 2, 1, 0, 0, 0, 1, 2, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 1,
       2, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, 2, 2, 2, 0, 0, 1, 1, 0, 2,
       1, 2, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 0, 2, 1,
       0, 0, 1, 0, 1, 2, 2, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 2, 2,
       1, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 2, 0, 1, 1, 1,
       2, 2, 0, 2, 1, 1, 2, 1, 2, 1, 2, 1, 0, 2, 0, 2, 2, 0, 0, 2, 2, 1,
       1, 0, 0, 0, 0, 2, 0, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 1, 2, 2,
       2, 1, 2, 1, 1, 0, 1, 2, 1, 1, 1, 2, 0, 0, 2, 1, 1, 1, 0, 0, 1, 2,
       2, 2, 2, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1,
       0, 2, 2, 1, 0, 2, 0, 2, 1, 1, 1, 1, 2, 2, 0, 1, 1, 2, 2, 2, 2, 2,
       2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 1, 1, 2, 1], d

# PCA Model - to reduce dimension

In [10]:
from sklearn.decomposition import PCA
from sklearn.datasets import make_blobs

In [11]:
n_sample=20
random_state=20

In [12]:
X,y=make_blobs(n_samples=n_sample,n_features=10,random_state=None)

In [13]:
X.shape

(20, 10)

In [14]:
# how do we reducer from 10 to 3

In [15]:
pca=PCA(n_components=3)

In [16]:
pca.fit(X)

PCA(n_components=3)

In [18]:
print(pca.explained_variance_ratio_)

[0.63772954 0.3320816  0.00985378]


In [19]:
first_pca=pca.components_[0]

In [20]:
print(first_pca)

[ 0.07154948  0.45315801  0.47774412 -0.25636789 -0.16825057  0.28976394
 -0.38594849 -0.22539537  0.41413833  0.10965073]


In [21]:
pca_reduced=pca.transform(X)

In [22]:
pca_reduced

array([[ -8.23306681,  12.30149967,   0.13392737],
       [ -9.71171599,  -8.75671532,   0.23555782],
       [ -5.87362307,  12.89025213,  -2.00862056],
       [ 18.29469969,  -1.46804732,  -1.73438523],
       [ 17.35920459,  -1.28540166,  -2.74399892],
       [ -6.78177138,  12.77251447,  -0.44080735],
       [-10.17382994,  -8.80285879,   2.40485193],
       [-10.7973969 ,  -8.91360092,   0.51202126],
       [ -5.69565386,  12.50030536,  -0.25102203],
       [-10.88428268,  -8.00333931,  -1.02187253],
       [ 16.32483512,  -1.16686124,   2.47842367],
       [ 16.1374441 ,  -1.14440532,   1.01054124],
       [-10.86768311,  -9.7430335 ,  -0.61868521],
       [ -7.23300314,  13.57810541,   1.83286594],
       [ -7.73969707,  11.18704704,   0.56632019],
       [ 14.61791335,  -1.63887482,  -0.02745007],
       [ 17.30120555,  -2.25190778,   2.75315668],
       [-10.51750071, -10.90166826,  -1.85470903],
       [ 15.92097425,  -1.35040989,  -1.50596012],
       [-11.44705201,  -9.80259